apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-web-yaml-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tarun-asthana/java-web-app-ci.git
    targetRevision: main  # or any branch name you use
    path: yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
