apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
