apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-web
  template:
    metadata:
      labels:
        app: java-web
    spec:
      containers:
      - name: java-web
        image: nginx:latest
        ports:
        - containerPort: 80
