name: Java CI for Web App
on:  #events to trigger the workflow
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4 # Standard Github Action for pulling source code
