name: Java CI Pipeline

on:
  push:
    branches: ['main']
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    branches: ['main']
    paths:
      - 'src/**'
      - 'pom.xml'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testing
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Verify Java and Maven Version
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -v

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build and Test with Maven
        run: mvn clean install

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Package Surefire Reports (if present)
        if: always()
        run: |
          if [ -d target/surefire-reports ]; then
            echo "Found test reports. Archiving..."
            tar -czf surefire-reports.tar.gz target/surefire-reports
          else
            echo "No test reports found to archive."
          fi

      - name: Upload Test Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: surefire-reports.tar.gz
