name: Java CI Pipeline

on:
  push:
    branches: ['main']
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    branches: ['main']
    paths:
      - 'src/**'
      - 'pom.xml'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Verify Java and Maven Version
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -v

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build and Test with Maven
        run: mvn clean install

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload Test Reports
        if: always()
        run: |
          if [ -d target/surefire-reports ]; then
            echo "Uploading test reports..."
          else
            echo "No surefire-reports directory found."
          fi

      - name: Upload Surefire Reports as Artifact
        if: always() && exists('target/surefire-reports')
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports
