name: Java CI Pipeline

on:
  push:
    branches: ['main']
    paths:
    - 'src/**'
    - 'pom.xml'
  pull_request:
    branches: ['main']
    paths:
    - 'src/**'
    - 'pom.xml'

jobs:
  build:
    runs-on: tarun
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        java: [11, 17]

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testing
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        continue-on-error: true






    
