name: Java CI Pipeline

on:
  push:
    branches: ['main']
    paths:
    - 'src/**'
    - 'pom.xml'
  pull_request:
    branches: ['main']
    paths:
    - 'src/**'
    - 'pom.xml'

jobs:
  build:
    runs-on: tarun
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        java: [11, 17]





    
