name: Java CI Pipeline

on:
  push:
    branches: ['main']
    paths:
    - 'src/**'
    - 'pom.xml'
  pull_request:
    branches: ['main']
    paths:
    - 'src/**'
    - 'pom.xml'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: tarun
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        java: [17]


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven


      - name: Verify Java and Maven Version
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -v


      

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        continue-on-error: true

      - name: Upload Test Reports
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.java }}
          path: target/surefire-reports/






    
