name: Java CI Pipeline

on:
  push:
    branches: ['main']
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    branches: ['main']
    paths:
      - 'src/**'
      - 'pom.xml'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    uses: tarun-asthana/github-actions-shared/.github/workflows/java-build.yml@main
    with:
      java_version: '17'


 
