name: Java CI Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'pom.xml'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        java: [11, 17]

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Verify Java and Maven Version
        run: |
         echo "JAVA_HOME=$JAVA_HOME"
         java -version
         mvn -v


      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Run Tests
        run: mvn test

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: build-jar-${{ matrix.java }}
          path: target/*.jar

      - name: Upload Test Reports
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.java }}
          path: target/surefire-reports/

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          packs: codeql/java-queries,security-extended,codeql/java-experimental-atm

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        continue-on-error: true
