
name: Upload Artifact
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
    timeout-minutes: 1
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 # Standard Github Action for pulling source code

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: echo "I am alive !!!" ; sleep 60;

 test:
   runs-on: my-self-hosted-runner
