name: Upload Artifact
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test with Maven
        run: mvn -B clean verify

      - name: Upload build artifact
        uses: actions/upload-artifact@v4 # standard Github Action for artifact upload
        with:
          name: web-app-war
          path: target/*.war
