
name: Upload Artifact
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4 # Standard Github Action for pulling source code

      - name: set up JDK 17
        uses: actions/setup-java@v4
        timeout-minutes: 0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: echo "I am alive !!!"
 
