name: Upload Artifact
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: Ajay
    concurrency:
      group: build-group
      cancel-in-progress: true
    timeout-minutes: 1
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 # Standard Github Action for pulling source code

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: echo ${{ secrets.ABCD}}; echo ${{ vars.EFGH}};
      - name: Branch Check
        run: |
          if ["${{ github.ref }}"] == "refs/heads/main" ]; then
            echo "Main branch"
          else
            echo "Not Main branch"
          fi

